### ISSUE TITLE
run_tests.sh doesn't run on OS X

### ISSUE THREAD

**Issue by jpsim** [benloong/TidyJSON#1]
How do you think we could go about testing with `corelibs-xctest` on OS X. The `run_tests.sh` script seems to work fine on Linux, but it would be valuable to do the same on Darwin.

Thanks for a great project!

**Comment by benloong** [comment]
@jpsim  OS X newest Xcode Swift version is 2.1.1 and it seems not support `swift build` command, currently I can't figure out how to build project without Xcode project. I will run on it. :)

**Comment by jpsim** [comment]
I didn't mean with Swift 2.1.1 that comes with Xcode, I meant with the swift distribution from swift.org, which certainly does support `swift build`.

**Comment by benloong** [comment]
@jpsim  No, OS X Swift miss `swift-build` command. I downloaded `swift-2.2-SNAPSHOT-2016-01-25-a-osx.pkg` from swift.org and run `swift build` failed. 

`error: unable to invoke subcommand: /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-25-a.xctoolchain/usr/bin/swift-build (No such file or directory)`

**Comment by jpsim** [comment]
That's strange, it's working fine for us over at https://github.com/jpsim/SourceKitten/pull/150, https://github.com/realm/SwiftLint/pull/462 and https://github.com/Carthage/Commandant/pull/50.

**Comment by benloong** [comment]
Looks like a custom `Makefile` script needed to build. :+1:

**Comment by jpsim** [comment]
No, that's just really because of the non-default system modules used by those projects (clang & SourceKit). It's definitely possible to do without Makefiles. Anyway, I stumbled upon your project in the search for how to run XCTest from OSS Swift distributions, hoping one of us figures this out and can share with the other! :smile:

**Comment by benloong** [comment]
@jpsim  Oh. `swift build` only contained in `Development` version. i downloaded false version. :smile:

**Comment by benloong** [comment]
hi @jpsim. good news. `swift build` `swift test` works correctly under version [swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a](https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg) take a look at `.travis.yml` of develop branch.

**Comment by jpsim** [comment]
:+1: thanks for updating this!
