### ISSUE TITLE
init? with Any

### ISSUE THREAD

**Issue by dileping** [benloong/TidyJSON#2]
Hi guys, great job!

I'm interested in replacing our current library choice with TidyJSON for our project [Swift Express](https://github.com/crossroadlabs/Express).

What I really miss here is a constructor with `Any` argument, something like:

``` swift
init(any:Any?) throws
```

or

``` swift
init?(any:Any?)
```

or may be even always succeeding `init`, but being your built-in null if failed.

`Any` can be anything supported, like `Dictionary`, `String`, whatever...

Do you consider adding something like this?

Thanks in advance!

**Comment by dileping** [comment]
Actually I already have implemented it inside [Express](https://github.com/crossroadlabs/Express). Let me know if you would like to have it inside TidyJSON.

**Comment by benloong** [comment]
@dileping  `Any` and `AnyObject` are not type safe, while `TidyJSON` is designed to be static type safe, so we will not add those constructors to `TidyJSON` lib.   Some extension methods to implement it is a good way.

**Comment by dileping** [comment]
@benloong OK, I still can live with it :) Thanks for all the great job!
